<Project Sdk="Godot.NET.Sdk/3.3.0">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>PereSkyroom</RootNamespace>
    <AssemblyName>PereSkyroom</AssemblyName>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='ExportDebug|AnyCPU'">
    <DefineConstants>TRACE;DEBUG;GODOT;GODOT_WINDOWS;GODOT_PC;GODOT_EXPORT</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='ExportRelease|AnyCPU'">
    <DefineConstants>TRACE;GODOT;GODOT_WINDOWS;GODOT_PC;GODOT_EXPORT</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BlenderReader\BlenderReader.csproj" />
  </ItemGroup>
</Project>
